{
  "providers": ["python"],
  "phases": {
    "install": {
      "cmds": [
        "pip install --upgrade pip",
        "pip install -r api/requirements.txt"
      ]
    },
    "build": {
      "cmds": []
    }
  },
  "start": {
    "cmd": "cd api && uvicorn main:app --host 0.0.0.0 --port $PORT"
  }
}

